version: "2"

services:
    cloudwatch_validator:
        build: ${PROJECT_ROOT}/integ/validate_cloudwatch
        environment:
            - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
            - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
            - "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
            - "TAG=${TAG}"
            - "REGION=${REGION}"
