version: "2"

services:
    clean-cw:
        build: ./clean_cloudwatch
        environment:
            - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
            - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
            - "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
            - "REGION=${REGION}"
